version = 0.1

[default.deploy.parameters]
stack_name = "adaptive-test-engine-v2"
resolve_s3 = true
s3_prefix = "adaptive-test-engine-v2"
resolve_image_repos = true
region = "us-east-1"
profile = "account2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

[default.global.parameters]
region = "us-east-1"
